trigger:
  - master
  - development

resources:
  repositories:
  - repository: template
    type: git
    name: PipelineTemplates

pool:
  vmImage: ubuntu-16.04

container:
  image: maven:3.6.1-jdk-8-slim

steps:
- template: maven.yml@template
  parameters:
    mavenGoals: clean deploy
    mavenSkipTests: true
    mavenProfiles: ado
